runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /images
  static_dir: images
- url: /audio
  static_dir: audio
- url: /compass
  static_dir: compass
- url: /scripts
  static_dir: scripts
- url: /.*
  script: main.app
